Feature: Create MHR document

  Background:
    * def result = call read('classpath:lucid/auth/TherapistAuth.feature')
    * def user = result.response
    * def token = user.access
    * header Authorization = 'Bearer ' + token

    Given url `${baseUrl}/onboarding/api/contact_profile/`
    * header Authorization = 'Bearer ' + token
    And params { email: 'qapatient01@lucidlane.com' }
    When method GET
    Then status 200
    And def patient = response.results[0].id
    And def sourceId = response.results[0].id
    And def SourceName = response.results[0].id

    Given url `${baseUrl}/therapist/api/therapist/current/`
    * header Authorization = 'Bearer ' + token
    When method GET
    Then status 200
    And def CreatorId = response.Id


  @smoke
  Scenario Outline: Create MHR with status
    Given url baseUrl+'/patients/api/document/'
    * header Authorization = 'Bearer ' + token

    And def requestBody =
  """
{
    "contact_profile":#(patient),
    "metadata": {
        "mhr_marketing_copy": "<p>Thank you for referring this patient to us at Lucid Lane. Future reports will include health signal data across all health checks. Lucid Lane&rsquo;s proprietary analytics engine will provide instant, real-time outcomes that are essential for your practice&rsquo;s electronic records.<br /><br />In addition, Member&rsquo;s health checks for depression, anxiety, pain thoughts and daily living may show decline. These scores need to be taken into context with member&rsquo;s level of disengagement, commitment over time and barriers to progress such as environmental factors and external stressors.</p>",
        "nextAppointmentSession": "05/26/2023",
        "narrative_summary_text": "Testing narrative summary ",
        "patient_appointments": {
            "deletedAppointments": [],
            "addedAppointments": []
        },
        "diagnosis_codes": "F41.1 - Generalized Anxiety Disorder\nF43.10 - Post-Traumatic Stress Disorder - Unspecified\nF43.12 - Post-Traumatic Stress Disorder - Chronic\nF43.22 - Adjustment Disorder with Anxiety\nF45.42 - Pain Disorder with Related Psychological Factors\nF80.2 - Mixed Receptive-Expressive Language Disorder\nZ63.0 - Problems in Relationship with Spouse or Partner\nZ71.3 - Dietary Counseling and Surveillance",
        "source": {
            "id": #(sourceId),
            "name": #(sourceName),
            "fax_phone_no": [
                "833-852-0387"
            ],
            "delivery_method": [
                "fax",
                "email"
            ],
            "contact_email": [
                "qatherapist01@lucidlane.com"
            ]
        }
    },
    "creator": #(CreatorId),
    "filename": "<file_name>",
    "object_type": 2,
    "version": "v3",
    "name": "HEALTH REPORT",
    "status": "<status>",
    "report_type": "<report_type>",
    "md_recommendation_note": "<p>In response to your e-consult request, we will continue to provide monthly tapering recommendations based on the patient's weekly therapy sessions, health signals, and withdrawal symptoms. Tapering recommendations are generated by our artificial intelligence platform that aggregates health signals and patient data to provide a customized taper recommendation to maximize success. These recommendations are reviewed by a physician and/or pharmacy tapering specialist and adjusted accordingly and will be provided until you opt out of the e-consult program.</p>"
}
  """
    And request requestBody
    When method POST
    Then status 201
    And assert response.contact_profile == patient

    Examples:
      |file_name|status|report_type|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Preview|2|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Pending Approval|2|
      |QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Approved|3|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Preview|3|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Pending Approval|3|
      |QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Approved|3|

  @smoke
  Scenario Outline: Create MHR and Get MHR Document details
    Given url baseUrl+'/patients/api/document/'
    * header Authorization = 'Bearer ' + token
    * def delivery_status = "pdf_generation"

    And def requestBody =
  """
{
    "contact_profile":#(patient),
    "metadata": {
      "mhr_marketing_copy": "<p>Thank you for referring this patient to us at Lucid Lane. Future reports will include health signal data across all health checks. Lucid Lane&rsquo;s proprietary analytics engine will provide instant, real-time outcomes that are essential for your practice&rsquo;s electronic records.<br /><br />In addition, Member&rsquo;s health checks for depression, anxiety, pain thoughts and daily living may show decline. These scores need to be taken into context with member&rsquo;s level of disengagement, commitment over time and barriers to progress such as environmental factors and external stressors.</p>",
      "nextAppointmentSession": [],
      "narrative_summary_text": [],
      "patient_appointments": {
        "deletedAppointments": [],
        "addedAppointments": []
      },
      "diagnosis_codes": "F41.1 - Generalized Anxiety Disorder\nF43.10 - Post-Traumatic Stress Disorder - Unspecified\nF43.12 - Post-Traumatic Stress Disorder - Chronic\nF43.22 - Adjustment Disorder with Anxiety\nF45.42 - Pain Disorder with Related Psychological Factors\nF80.2 - Mixed Receptive-Expressive Language Disorder\nZ63.0 - Problems in Relationship with Spouse or Partner\nZ71.3 - Dietary Counseling and Surveillance",
      "source": {
        "id": #(sourceId),
        "name": #(sourceName),
        "fax_phone_no": [
          "833-852-0387"
        ],
        "delivery_method": [
          "fax",
          "email"
        ],
        "contact_email": [
          "qatherapist01@lucidlane.com"
        ]
      }
    },
    "creator": #(CreatorId),
    "filename": "<file_name>",
    "object_type": 2,
    "version": "v3",
    "name": "HEALTH REPORT",
    "status": "<status>",
    "report_type": "<report_type>",
    "md_recommendation_note": "<p>In response to your e-consult request, we will continue to provide monthly tapering recommendations based on the patient's weekly therapy sessions, health signals, and withdrawal symptoms. Tapering recommendations are generated by our artificial intelligence platform that aggregates health signals and patient data to provide a customized taper recommendation to maximize success. These recommendations are reviewed by a physician and/or pharmacy tapering specialist and adjusted accordingly and will be provided until you opt out of the e-consult program.</p>"
  }
  """
    And request requestBody
    When method POST
    Then status 201
    And assert response.document_details.delivery_status == delivery_status
    And assert response.metadata != null
    And assert response.contact_profile == patient
    And assert response.creator == CreatorId
    ##* print response.document_details.delivery_status

    #Fetch Document id from the response
    * def document_id = $.id
    * print document_id

    Given url baseUrl+'/patients/api/mhr_document_details/' + document_id + '/'
    * header Authorization = 'Bearer ' + token
    And method Get
    Then status 200

    Examples:
      | file_name |status|report_type|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Preview|2|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Pending Approval|2|
      |QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Approved|2|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Preview|3|
      |DRAFT-QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Pending Approval|3|
      |QA-Patient-01_Monthly-Member-Health-Report-testing_05-24-2023_Mukarram|Approved|3|


